// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SavingBack.Database;

#nullable disable

namespace SavingBack.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214184549_AgregandoColumnaFotoPerfil")]
    partial class AgregandoColumnaFotoPerfil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SavingBack.Models.Ahorro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MetaAhorroId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetaAhorroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ahorro");
                });

            modelBuilder.Entity("SavingBack.Models.CategoriaGasto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriaGasto");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nombre = "Alimentación"
                        },
                        new
                        {
                            Id = 2L,
                            Nombre = "Transporte"
                        },
                        new
                        {
                            Id = 3L,
                            Nombre = "Salud"
                        },
                        new
                        {
                            Id = 4L,
                            Nombre = "Hogar"
                        },
                        new
                        {
                            Id = 5L,
                            Nombre = "Servicios"
                        },
                        new
                        {
                            Id = 6L,
                            Nombre = "Educación"
                        },
                        new
                        {
                            Id = 7L,
                            Nombre = "Entretenimiento"
                        },
                        new
                        {
                            Id = 8L,
                            Nombre = "Mascotas"
                        },
                        new
                        {
                            Id = 9L,
                            Nombre = "Ropa"
                        },
                        new
                        {
                            Id = 10L,
                            Nombre = "Deudas"
                        },
                        new
                        {
                            Id = 11L,
                            Nombre = "Inversiones"
                        },
                        new
                        {
                            Id = 12L,
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("SavingBack.Models.MetaAhorro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MontoActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoObjetivo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MetaAhorro", t =>
                        {
                            t.HasCheckConstraint("CK_MetaAhorro_Estado", "Estado IN ('Activa', 'Cumplida', 'Cancelada')");
                        });
                });

            modelBuilder.Entity("SavingBack.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptaTerminos")
                        .HasColumnType("bit");

                    b.Property<long>("Cedula")
                        .HasColumnType("bigint");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ManejaGastos")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", t =>
                        {
                            t.HasCheckConstraint("CK_Usuario_Rol", "Rol IN ('Cliente', 'Admin')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AceptaTerminos = true,
                            Cedula = 1001944317L,
                            Contrasena = "+osxdTMbvrdSIPgNenMgtQ==",
                            Correo = "Salinitosnelson@gmail.com",
                            FechaNacimiento = new DateTime(2001, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfil = "/Fotos/default.png",
                            ManejaGastos = false,
                            NombreUsuario = "Root",
                            PrimerApellido = "",
                            PrimerNombre = "Admin",
                            Rol = "Admin"
                        });
                });

            modelBuilder.Entity("SavingBack.Models.Ahorro", b =>
                {
                    b.HasOne("SavingBack.Models.MetaAhorro", "MetaAhorro")
                        .WithMany("Ahorros")
                        .HasForeignKey("MetaAhorroId");

                    b.HasOne("SavingBack.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaAhorro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SavingBack.Models.MetaAhorro", b =>
                {
                    b.HasOne("SavingBack.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SavingBack.Models.MetaAhorro", b =>
                {
                    b.Navigation("Ahorros");
                });
#pragma warning restore 612, 618
        }
    }
}
