// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SavingBack.Database;

#nullable disable

namespace SavingBack.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410213530_AñadiendoLogicaEnAhorro")]
    partial class AñadiendoLogicaEnAhorro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SavingBack.Models.Ahorro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetaAhorroId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetaAhorroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ahorro", t =>
                        {
                            t.HasCheckConstraint("CK_Ahorro_Tipo", "[Tipo] IN ('Efectivo', 'Nequi', 'Banco')");
                        });
                });

            modelBuilder.Entity("SavingBack.Models.CategoriaGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriaGasto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Alimentación"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Transporte"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Salud"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Hogar"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Servicios"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Educación"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Entretenimiento"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Mascotas"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Ropa"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Deudas"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Inversiones"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Otros"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Movimiento Interno"
                        });
                });

            modelBuilder.Entity("SavingBack.Models.Egreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaGastoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaGastoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Egreso", t =>
                        {
                            t.HasCheckConstraint("CK_Egreso_Tipo", "[Tipo] IN ('Efectivo', 'App', 'Nequi', 'Banco')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaGastoId = 1,
                            FechaRegistro = new DateTime(2026, 4, 10, 16, 35, 28, 899, DateTimeKind.Local).AddTicks(5668),
                            Monto = 100000,
                            Tipo = "Nequi",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaGastoId = 4,
                            FechaRegistro = new DateTime(2026, 4, 10, 16, 35, 28, 899, DateTimeKind.Local).AddTicks(5674),
                            Monto = 8000,
                            Tipo = "App",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoriaGastoId = 10,
                            FechaRegistro = new DateTime(2026, 4, 10, 16, 35, 28, 899, DateTimeKind.Local).AddTicks(5678),
                            Monto = 12000,
                            Tipo = "Efectivo",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoriaGastoId = 5,
                            FechaRegistro = new DateTime(2026, 4, 10, 16, 35, 28, 899, DateTimeKind.Local).AddTicks(5682),
                            Monto = 60000,
                            Tipo = "Efectivo",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoriaGastoId = 2,
                            FechaRegistro = new DateTime(2026, 4, 10, 16, 35, 28, 899, DateTimeKind.Local).AddTicks(5686),
                            Monto = 180000,
                            Tipo = "Banco",
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("SavingBack.Models.Ingreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ingreso", t =>
                        {
                            t.HasCheckConstraint("CK_Ingreso_Tipo", "[Tipo] IN ('Efectivo', 'App', 'Nequi', 'Banco')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaRegistro = new DateTime(2026, 4, 10, 16, 35, 28, 899, DateTimeKind.Local).AddTicks(5040),
                            Monto = 10000,
                            Tipo = "Efectivo",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            FechaRegistro = new DateTime(2026, 4, 10, 16, 35, 28, 899, DateTimeKind.Local).AddTicks(5044),
                            Monto = 80000,
                            Tipo = "Nequi",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 3,
                            FechaRegistro = new DateTime(2026, 4, 10, 16, 35, 28, 899, DateTimeKind.Local).AddTicks(5048),
                            Monto = 120000,
                            Tipo = "App",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 4,
                            FechaRegistro = new DateTime(2026, 4, 10, 16, 35, 28, 899, DateTimeKind.Local).AddTicks(5052),
                            Monto = 66000,
                            Tipo = "Efectivo",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 5,
                            FechaRegistro = new DateTime(2026, 4, 10, 16, 35, 28, 899, DateTimeKind.Local).AddTicks(5055),
                            Monto = 150000,
                            Tipo = "Banco",
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("SavingBack.Models.MetaAhorro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MontoActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoObjetivo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MetaAhorro", t =>
                        {
                            t.HasCheckConstraint("CK_MetaAhorro_Estado", "Estado IN ('Activa', 'Cumplida', 'Cancelada')");
                        });
                });

            modelBuilder.Entity("SavingBack.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptaTerminos")
                        .HasColumnType("bit");

                    b.Property<long>("Cedula")
                        .HasColumnType("bigint");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ManejaGastos")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", t =>
                        {
                            t.HasCheckConstraint("CK_Usuario_Rol", "Rol IN ('Cliente', 'Admin')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AceptaTerminos = true,
                            Cedula = 1001944317L,
                            Contrasena = "+osxdTMbvrdSIPgNenMgtQ==",
                            Correo = "Salinitosnelson@gmail.com",
                            FechaNacimiento = new DateTime(2001, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoPerfil = "/Uploads/Fotos/default.png",
                            ManejaGastos = false,
                            NombreUsuario = "Root",
                            PrimerApellido = "",
                            PrimerNombre = "Admin",
                            Rol = "Admin"
                        });
                });

            modelBuilder.Entity("SavingBack.Models.Ahorro", b =>
                {
                    b.HasOne("SavingBack.Models.MetaAhorro", "MetaAhorro")
                        .WithMany("Ahorros")
                        .HasForeignKey("MetaAhorroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SavingBack.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaAhorro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SavingBack.Models.Egreso", b =>
                {
                    b.HasOne("SavingBack.Models.CategoriaGasto", "CategoriaGasto")
                        .WithMany()
                        .HasForeignKey("CategoriaGastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SavingBack.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaGasto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SavingBack.Models.Ingreso", b =>
                {
                    b.HasOne("SavingBack.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SavingBack.Models.MetaAhorro", b =>
                {
                    b.HasOne("SavingBack.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SavingBack.Models.MetaAhorro", b =>
                {
                    b.Navigation("Ahorros");
                });
#pragma warning restore 612, 618
        }
    }
}
